[package]
name = "silent-chrome"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
secpref-kit = { git = "https://github.com/shxve/secpref-kit", rev = "23a8e7c163ccb1c774bdf3bcff5dbc97fcd9b15d" }
tempfile = "3"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"

[profile.release]
lto = "fat"
strip = "symbols"
panic = "abort"
opt-level = "z"
codegen-units = 1
